### ISSUE TITLE
Markers showing as unknown when tapping marker

### ISSUE THREAD

**Issue by cmlaird** [flighttactics/TAKAware#53]
**Describe the bug**
User markers are sometimes showing as Unknown when tapping the marker even though the callsign on the map shows correctly. 

![image](https://github.com/user-attachments/assets/4599443f-b0a5-4651-aa40-9c9457152c53)

**Smartphone (please complete the following information):**
 - Version: [e.g. 22]
 - App Store or TestFlight?: 

**Additional context**

**Comment by CoryFoy** [comment]
This was likely fixed with https://github.com/flighttactics/TAKAware/commit/cee4ce549b3d9bf04cb7c0a172bef74587a3dd8c and I have not seen it in any of the latest version or App Store version. Closing unless it comes back up
